/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ConcurrencyThread;

public class App {

    public static void main(String[] args) {
        Thread thread = new Thread(new Runnable() {

            @Override
            public void run() {
                for (int i=0; i<7; i++){
                    System.out.println("Worker Thread Printing Number: " + i);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
                
            }
            
        });

        thread.start();


        for (int i=0; i<7; i++){
            System.out.println("Main Thread Printing Number: " + i);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}
