# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: mainuldip
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 7001:8080

volumes:
  pgsqldata:



# docker-compose -f docker-compose-postgres.yaml up -d